### ISSUE TITLE
where does ChainCRF come from?

### ISSUE THREAD

**Issue by liaoming999** [LopezGG/Sequence-Labelling#1]
There is no such file in the keras.layers called "ChainCRF". Where does it come from? Thank you

**Comment by LopezGG** [comment]
from keras.layers import ChainCRF. Check this thread
https://github.com/fchollet/keras/issues/4090

**Comment by LopezGG** [comment]
I moved to a TF implementation so no longer correcting this code
the tf version is here
https://github.com/LopezGG/NN_NER_tensorFlow
