### ISSUE TITLE
i want to know what is version of the keras in your code thank you 

### ISSUE THREAD

**Issue by ninggege123** [LopezGG/Sequence-Labelling#2]

**Comment by LopezGG** [comment]
Sorry. I moved to tensorflow. I  can send you the tf implementation of the same model if you would like

**Comment by peipei1109** [comment]
@LopezGG  Can send the tf implementation to me？ thanks

**Comment by bhavsarpratik** [comment]
Hi @LopezGG Can you send me the tensorflow implementation at pratik.a.bhavsar@gmail.com
Thanks!

**Comment by odek53r** [comment]
I need the tensorflow version code. My email is odek53r@gmail.com. Thank you!

**Comment by sanjaymeena** [comment]
@LopezGG  Hello, Can  you also send me tensorflow version of code . My email is sanjaymeena@gmail.com. Thanks!!

**Comment by LopezGG** [comment]
Please Find a basic Version here
https://github.com/LopezGG/NN_NER_tensorFlow
